const maps = {
    map0: [ 
        '  WWWWW ',  
        'WWW   W ',  
        'WOSB  W ',  
        'WWW BOW ',  
        'WOWWB W ',  
        'W W O WW',  
        'WB XBBOW',  
        'W   O  W',  
        'WWWWWWWW'],
    map1: [
        '    WWWWW          ',
        '    W   W          ',
        '    WB  W          ',
        '  WWW  BWW         ',
        '  W  B B W         ',
        'WWW W WW W   WWWWWW',
        'W   W WW WWWWW  OOW',
        'W B  B          OOW',
        'WWWWW WWW WSWW  OOW',
        '    W     WWWWWWWWW',
        '    WWWWWWW        '],
    map2: [
        '   WWWWWWWWWWWW    ',
        '   WOO  W     WWW  ',
        '   WOO  W B  B  W  ',
        '   WOO  WBWWWW  W  ',
        '   WOO    S WW  W  ',
        '   WOO  W W  B WW  ',
        '   WWWWWW WWB B W  ',
        '     W B  B B B W  ',
        '     W    W     W  ',
        '     WWWWWWWWWWWW  '],
    map3: [
        '         WWWWWWWW  ',
        '         W     SW  ',
        '         W BWB WW  ',
        '         W B  BW   ',
        '         WWB B W   ',
        ' WWWWWWWWW B W WWW ',
        ' WOOOO  WW B  B  W ',
        ' WWOOO    B  B   W ',
        ' WOOOO  WWWWWWWWWW ',
        ' WWWWWWWW          '],
    map4: [
        '           WWWWWWWW',
        '           W  OOOOW',
        'WWWWWWWWWWWW  OOOOW',
        'W    W  B B   OOOOW',
        'W BBBWB  B W  OOOOW',
        'W  B     B W  OOOOW',
        'W BB WB B BWWWWWWWW',
        'W  B W     W       ',
        'WW WWWWWWWWW       ',
        'W    W    WW       ',
        'W     B   WW       ',
        'W  BBWBB  SW       ',
        'W    W    WW       ',
        'WWWWWWWWWWW        '],
    map5: [
        '         WWWWW     ',
        '         W   WWWWW ',
        '         W WBWW  W ',
        '         W     B W ',
        ' WWWWWWWWW WWW   W ',
        ' WOOOO  WW B  BWWW ',
        ' WOOOO    B BB WW  ',
        ' WOOOO  WWB  B SW  ',
        ' WWWWWWWWW  B  WW  ',
        '         W B B  W  ',
        '         WWW WW W  ',
        '           W    W  ',
        '           WWWWWW  '],
    map6: [
        '    WWWWWW  WWW    ',
        '    WOO  W WWSWW   ',
        '    WOO  WWW   W   ',
        '    WOO     BB W   ',
        '    WOO  W W B W   ',
        '    WOOWWW W B W   ',
        '    WWWW B WB  W   ',
        '       W  BW B W   ',
        '       W B  B  W   ',
        '       W  WW   W   ',
        '       WWWWWWWWW   '],
    map7: [
        '           WWWWW   ',
        '     WWWWWWW   WW  ',
        '    WW W SWW BB W  ',
        '    W    B      W  ',
        '    W  B  WWW   W  ',
        '    WWW WWWWWBWWW  ',
        '    W B  WWW OOW   ',
        '    W B B B OOOW   ',
        '    W    WWWOOOW   ',
        '    W BB W WOOOW   ',
        '    W  WWW WWWWW   ',
        '    WWWW           '],
    map8: [
        '    WWWW           ',
        '    W  WWWWWWWWWWW ',
        '    W    B   B B W ',
        '    W BW B W  B  W ',
        '    W  B B  W    W ',
        '  WWW BW W  WWWW W ',
        '  WSWB B B  WW   W ',
        '  W    B WBW   W W ',
        '  W   B    B B B W ',
        '   WWWW  WWWWWWWWW ',
        '    W      W       ',
        '    W      W       ',
        '    WOOOOOOW       ',
        '    WOOOOOOW       ',
        '    WOOOOOOW       ',
        '    WWWWWWWW       '],
    map9: [
        '           WWWWWWW ',
        '           W  OOOW ',
        '       WWWWW  OOOW ',
        '       W      O OW ',
        '       W  WW  OOOW ',
        '       WW WW  OOOW ',
        '      WWW WWWWWWWW ',
        '      W BBB WW     ',
        '  WWWWW  B B WWWWW ',
        ' WW   WB B   W   W ',
        ' WS B  B    B  B W ',
        ' WWWWWW BB B WWWWW ',
        '      W      W     ',
        '      WWWWWWWW     '],
    map10: [
        ' WWW  WWWWWWWWWWWWW',
        'WWSWWWW       W   W',
        'W BB   BB  B B OOOW',
        'W  BBBW    B  WOOOW',
        'W B   W BB BB WOOOW',
        'WWW   W  B    WOOOW',
        'W     W B B B WOOOW',
        'W    WWWWWW WWWOOOW',
        'WW W  W  B B  WOOOW',
        'W  WW W BB B BWWOOW',
        'W OOW W  B      WOW',
        'W OOW W BBB BBB WOW',
        'WWWWW W       W WOW',
        '    W WWWWWWWWW WOW',
        '    W           WOW',
        '    WWWWWWWWWWWWWWW'],
    map11: [
        '          WWWW     ',
        '     WWWW W  W     ',
        '   WWW  WWWB W     ',
        '  WW   S  B  W     ',
        ' WW  B BBWW WW     ',
        ' W  WBWW     W     ',
        ' W W B BB W WWW    ',
        ' W   B W  W B WWWWW',
        'WWWW    W  BB W   W',
        'WWWW WW B         W',
        'WO    WWW  WWWWWWWW',
        'WOO OOW WWWW       ',
        'WOOOWOW            ',
        'WOOOOOW            ',
        'WWWWWWW            '],
    map12: [
        ' WWWWWWWWWWWWWWWW  ',
        ' W              W  ',
        ' W W WWWWWW     W  ',
        ' W W  B B B BW  W  ',
        ' W W   BSB   WW WW ',
        ' W W WB B BWWWOOOW ',
        ' W W   B B  WWOOOW ',
        ' W WWWBBB B WWOOOW ',
        ' W     W WW WWOOOW ',
        ' WWWWW   WW WWOOOW ',
        '     WWWWW     WWW ',
        '         W     W   ',
        '         WWWWWWW   '],
    map13: [
        '   WWWWWWWWW       ',
        '  WW   WW  WWWWW   ',
        'WWW     W  W    WWW',
        'W  B WB W  W  OOO W',
        'W W BWSBWW W WOWO W',
        'W  W WB  W    O O W',
        'W B    B W W WOWO W',
        'W   WW  WWB B O O W',
        'W B W   W  WBWOWO W',
        'WW B  B   B  BOOO W',
        ' WB WWWWWW    WW  W',
        ' W  W    WWWWWWWWWW',
        ' WWWW              '],
    map14: [
        '        WWWWWWW    ',
        '  WWWWWWW     W    ',
        '  W     W BSB W    ',
        '  WBB W   WWWWWWWWW',
        '  W WWWOOOOOOWW   W',
        '  W   BOOOOOOWW W W',
        '  W WWWOOOOOO     W',
        ' WW   WWWW WWW WBWW',
        ' W  WB   W  B  W W ',
        ' W  B BBB  W BWW W ',
        ' W   B B WWWBB W W ',
        ' WWWWW     B   W W ',
        '     WWW WWW   W W ',
        '       W     W   W ',
        '       WWWWWWWW  W ',
        '              WWWW '],
    map15: [
        '     WWWWWWW       ',
        '    W   W  W       ',
        '    W  B   W       ',
        '  WWW WB   WWWW    ',
        '  W  B  WWB   W    ',
        '  W  W S B W BW    ',
        '  W  W      B WWWW ',
        '  WW WWWWBWW     W ',
        '  W BWOOOOOW W   W ',
        '  W  BOOXXO BW WWW ',
        ' WW  WOOOOOW   W   ',
        ' W   WWW WWWWWWW   ',
        ' W BB  W  W        ',
        ' W  W     W        ',
        ' WWWWWW   W        ',
        '      WWWWW        '],
    map16: [
        '  WWWWW            ',
        '  W   WW           ',
        '  W    W  WWWW     ',
        '  W B  WWWW  W     ',
        '  W  BB B   BW     ',
        '  WWWS WB    WW    ',
        '   W  WW  B B WW   ',
        '   W B  WW WW OW   ',
        '   W  WBWWB  WOW   ',
        '   WWW   BOOWWOW   ',
        '    W    WOXOOOW   ',
        '    W BB WOOOOOW   ',
        '    W  WWWWWWWWW   ',
        '    W  W           ',
        '    WWWW           ',
        '                   '],
    map17: [
        '     WWWWWWWWWW    ',
        '     WOO  W   W    ',
        '     WOO      W    ',
        '     WOO  W  WWWW  ',
        '    WWWWWWW  W  WW ',
        '    W            W ',
        '    W  W  WW  W  W ',
        '  WWWW WW  WWWW WW ',
        '  W  B  WWWWW W  W ',
        '  W W B  B  W B  W ',
        '  W SB  B   W   WW ',
        '  WWWW WW WWWWWWW  ',
        '     W    W        ',
        '     WWWWWW        '],
    map18: [
        '     WWWWWWWWWWW   ',
        '     W  O  W   W   ',
        '     W WO    S W   ',
        ' WWWWW WWOOW WWWW  ',
        'WW  W OOWWW     WWW',
        'W B WOOO   B W  B W',
        'W    OO WW  WW WW W',
        'WWWWBWWBW B W   W W',
        '  WW W    WB BB W W',
        '  W  B W W  W BWW W',
        '  W               W',
        '  W  WWWWWWWWWWW  W',
        '  WWWW         WWWW'],
    map19: [
        '  WWWWWW           ',
        '  W   SWWWW        ',
        'WWWWW B   W        ',
        'W   WW    WWWW     ',
        'W B W  WW    W     ',
        'W B W  WWWWW W     ',
        'WW B  B    W W     ',
        'WW B B WWW W W     ',
        'WW W  B  W W W     ',
        'WW W WBW   W W     ',
        'WW WWW   W W WWWWWW',
        'W  B  WWWW W WOOOOW',
        'W    B    B   OOWOW',
        'WWWWB  BW B   OOOOW',
        'W       W  WW OOOOW',
        'WWWWWWWWWWWWWWWWWWW'],
    map20: [
        '    WWWWWWWWWW     ',
        'WWWWW        WWWW  ',
        'W     W   B  WS W  ',
        'W WWWWWWWBWWWW  WWW',
        'W W    WW W  WB OOW',
        'W W B  B  W  W  WOW',
        'W W B  W     WB OOW',
        'W W  WWW WW     WOW',
        'W WWW  W  W  WB OOW',
        'W W    W BWWWW  WOW',
        'W WB   B  B  WX OOW',
        'W    B W B B W  WOW',
        'WWWW BWWW    WX OOW',
        '   W    BB WWWOOOOW',
        '   W      WW WWWWWW',
        '   WWWWWWWW        '],
    map21: [
        '  WWWWWWWWW        ',
        '  W       W        ',
        '  W       WWWW     ',
        '  WW WWWW W  W     ',
        '  WW WSWW    W     ',
        '  W BBB B  BBW     ',
        '  W  W WW B  W     ',
        '  W  W WW  B WWWW  ',
        '  WWWW  BBB BW  W  ',
        '   W   WW   OOOOW  ',
        '   W W   W WOO OW  ',
        '   W   W W WWOOOW  ',
        '   WWWWW B  WOOOW  ',
        '       WW   WWWWW  ',
        '        WWWWW      '],
    map22: [
        'WWWWW      WWWW    ',
        'W    WWWWWWW  WWWWW',
        'W   BW  W  B  W   W',
        'W  B  B  B W B B  W',
        'WWB B   W SW B    W',
        'W  B WWWWWWWWWWW WW',
        'W W   WOOOOOOOW BW ',
        'W WW  W OOOOOOW  W ',
        'W W   BOOOOOOOOB W ',
        'W W B WOOOO OOW  W ',
        'W  B BWWWWBWWWW BW ',
        'W B   WWW B   B  WW',
        'W B     B B  B    W',
        'WW WWWWWW B WWWWW W',
        'W         W       W',
        'WWWWWWWWWWWWWWWWWWW'],
    map23: [
        '    WWWWWWW        ',
        '    W  W  WWWW     ',
        'WWWWW BWB W  WW    ',
        'WOO W  W  W   W    ',
        'WOO W BWB W  BWWWW ',
        'WO  W     WB  W  W ',
        'WOO   BW  W B    W ',
        'WOOSW  WB WB  W  W ',
        'WOO W BW     BW  W ',
        'WOO W  WBBWB  W  WW',
        'WOO W BW  W  BWB  W',
        'WOO W  W  W   W   W',
        'WWO WWWW  WWWWW   W',
        ' WWWW  WWWW   WWWWW'],
    map24: [
        'WWWWWWWWWWWWWWW    ',
        'WOOOOOOOOOO  OWWWW ',
        'WOOOOOOOOOOBBOW  W ',
        'WWWWWWWWWWWB W   WW',
        'W      B  B     B W',
        'WW WWWW   W  B W  W',
        'W      W   WW  W WW',
        'W  BW  W WW  WWW WW',
        'W B WBWWW    WWW WW',
        'WWW  B W  W  WWW WW',
        'WWW    B WW W  W WW',
        ' W B  W  B  B B   W',
        ' W  B  BWBBB  W   W',
        ' W  W  B      WWWWW',
        ' W SWW  W  W  W    ',
        ' WWWWWWWWWWWWWW    '],
    map25: [
        'WWWW               ',
        'W  WWWWWWWWWWWWWW  ',
        'W  W   OOWOOOOOOW  ',
        'W  W W WWWWW OOOW  ',
        'WWBW    OOOOOOOOW  ',
        'W   WWBWWWWWW  WWWW',
        'W B W     WWWWWWS W',
        'WWB W B   WWWWWW  W',
        'W  B WBBBWW       W',
        'W      W    WBWBWWW',
        'W WWWW WBBBBB    W ',
        'W W    B     W   W ',
        'W W   WW WW     WWW',
        'W WWWWWWBWWWWWW B W',
        'W        W    W   W',
        'WWWWWWWWWW    WWWWW'],
    map26: [
        '    WWWWWWW        ',
        '    W  W  WWWWW    ',
        '   WW  W  WOOOWWW  ',
        '   W  BW  WOOO  W  ',
        '   W B WBB OOO  W  ',
        '   W  BW  WOOO OW  ',
        '   W   W BWWWWWWWW ',
        '   WWB       B B W ',
        '   WW  W  BB W   W ',
        '    WWWWWW  WWBBSW ',
        '         W      WW ',
        '         WWWWWWWW  '],
    map27: [
        ' WWWWWWWWWWWWWWWWW ',
        ' WOOO   W    W   WW',
        'WWOOOOO  BWW W WB W',
        'WOOOOOOW  B  W    W',
        'WOOOOOOW  W  W W  W',
        'WWWWWWWWW B  B B  W',
        '  W     WBWWB WWBWW',
        ' WW   B    W B    W',
        ' W  WW WWW W  WWB W',
        ' W B BB     B  B  W',
        ' W B    BWWB WWWWWW',
        ' WWWWWWW  S WW     ',
        '       WWWWWW      '],
    map28: [
        '          WWWWW    ',
        '      WWWWW   W    ',
        '     WW B  B  WWWW ',
        ' WWWWW B  B B WWOW ',
        ' W       BB  WWOOW ',
        ' W  WWWWWW WWWOO W ',
        ' WW W  W    WOOO W ',
        ' W B   W    WOOO W ',
        ' WS WB WW WWWWOOOW ',
        ' WWWW  B BB  WWOOW ',
        '    WW  B B  BOOOW ',
        '     W BB  B W  OW ',
        '     W   B B  WWWW ',
        '     WWWWWW   W    ',
        '          WWWWW    '],
    map29: [
        'WWWWW              ',
        'W   WW             ',
        'W B  WWWWWWWWW     ',
        'WW W W       WWWWWW',
        'WW W   BWBWS  W   W',
        'W  W      B W   B W',
        'W  WWW WWWWWWWWW WW',
        'W  WW OOXOOOOO W WW',
        'WW WW XOXOOXOX W WW',
        'W BWWWWWWWWWW WWB W',
        'W  B   B  B    B  W',
        'W  W   W   W   W  W',
        'WWWWWWWWWWWWWWWWWWW'],
    map30: [
        '       WWWWWWWWWWW ',
        '       W   W     W ',
        'WWWWW  W     B B W ',
        'W   WWWWW BWW W WW ',
        'W B WW   W WW B  W ',
        'W B  SBB W WWBBB W ',
        'WW WWW   W WW    W ',
        'WW W   WWW WWWWWBW ',
        'WW W     B  WOOOOW ',
        'W  WWW WW B WOOOOWW',
        'W B   B W   WOOBO W',
        'W  WW B W  WWOOOO W',
        'WWWWW   WWWWWWOOOWW',
        '    WWWWW    WWWWW '],
    map31: [
        '   WWWW            ',
        '   W  WWWWWWWWW    ',
        '  WW  WW  W   W    ',
        '  W  BW BSB   WWWW ',
        '  WB  B  W B BW  WW',
        ' WW  BWW WB B     W',
        ' W  W  W W   BBB  W',
        ' W B    B  BWW WWWW',
        ' W B B WBW  W  W   ',
        ' WW  WWW  WWWB W   ',
        '  W  WOOOO     W   ',
        '  WWWWOOOOOOWWWW   ',
        '    WOOOOWWWW      ',
        '    WOOOWW         ',
        '    WOOOW          ',
        '    WWWWW          '],
    map32: [
        '         WWWW      ',
        '     WWWWW  W      ',
        '    WW     BW      ',
        '   WW B  WW WWW    ',
        '   WSB B W B  W    ',
        '   WWWW WW   BW    ',
        '    WOOOOWB B W    ',
        '    WOOOOW   BW    ',
        '    WOOOO  BB WW   ',
        '    WOOO W B   W   ',
        '    WWWWWWB B  W   ',
        '         W   WWW   ',
        '         WB WWW    ',
        '         W  W      ',
        '         WWWW      '],
    map33: [
        '   WWWWWWWWWWWW    ',
        '   WW     WW  W    ',
        '   WW   B   B W    ',
        '   WWWW WW BB W    ',
        '   W   B W    W    ',
        '   W BBB W WWWW    ',
        '   W   W W B WW    ',
        '   W  W  W  B W    ',
        '   W BW BW    W    ',
        '   W   OOW WWWW    ',
        '   WWWWOO B WSW    ',
        '   WOOOOOW BW W    ',
        '   WWOOOOW  B W    ',
        '   WWWOOWW    W    ',
        '   WWWWWWWWWWWW    ' ],
    map34: [
        '    WWWWWWWWW      ',
        '    WOOOO   WW     ',
        '    WOWOW  B WW    ',
        '   WWOOOOW W SWW   ',
        '   W OOOOW  W  WW  ',
        '   W     WB WWB W  ',
        '   WW WWW  B    W  ',
        '    WB  B B BW  W  ',
        '    W W  B B WW W  ',
        '    W  WWW  WW  W  ',
        '    W    WW WW WW  ',
        '    W  B W  B  W   ',
        '    WWWB B   WWW   ',
        '      W  WWWWW     ',
        '      WWWW         '],
    map35: [
        'WWWWWWWWWWWW WWWWWW',
        'W   W    W WWWOOOOW',
        'W   BBW   S  OOOOOW',
        'W   W WWW   W OOOOW',
        'WW WW WWW  W  OOOOW',
        ' W B B     W W WWWW',
        ' W  B BWW  W      W',
        'WWWW W  WWWW W WW W',
        'W  W WB   WW W    W',
        'W B  B  W WW W   WW',
        'W W B B    W W   W ',
        'W  B WW WW W WWWWW ',
        'W BB     BB  W     ',
        'WW WW WWW B  W     ',
        ' W    W W    W     ',
        ' WWWWWW WWWWWW     '],
    map36: [
        '            WWWWW  ',
        'WWWWW  WWWWWW   W  ',
        'W   WWWW  B B B W  ',
        'W B   WW WW WW  WW ',
        'W   B B     B  B W ',
        'WWW B  WW WW     WW',
        '  W WWWWW WWWWWBB W',
        ' WWBWWWWW SWW     W',
        ' W B  WWWBWWW B  WW',
        ' W B  W   WWW  WWW ',
        ' W BB B W   BB W   ',
        ' W     W   WW  W   ',
        ' WWWWWWWOO OWWW    ',
        '    WOOOOOOOOOW    ',
        '    WOOOOOOOOOW    ',
        '    WWWWWWWWWWW    '],
    map37: [
        'WWWWWWWWWWW        ',
        'WOOOOOO   WWWWWWWWW',
        'WOOOOOO   W  WW   W',
        'WOOWWW B    B     W',
        'WOOO B B W  WWW   W',
        'WOOOWBWWWWW    W  W',
        'WWW    W   WB  WB W',
        '  W  BB B B  BWW  W',
        '  W  B   WBWB WWB W',
        '  WWW WW W    WW  W',
        '   W  B B WW WWWWWW',
        '   W    B  B  W    ',
        '   WW   W W   W    ',
        '    WWWWWSWWWWW    ',
        '        WWW        '],
    map38: [
        '          WWWW     ',
        '    WWWWWWW SW     ',
        '    W     B  W     ',
        '    W   BWW BW     ',
        '    WWBWOOOW W     ',
        '     W BOOO  W     ',
        '     W WO OW WW    ',
        '     W   W WB W    ',
        '     WB  B    W    ',
        '     W  WWWWWWW    ',
        '     WWWW          '],
    map39: [
        '             WWWWWW',
        ' WWWWWWWWWWWWWOOOOW',
        'WW   WW     WWOOOOW',
        'W  BBWW  B SWWOOOOW',
        'W      BB BW  OOOOW',
        'W  B WW BB W W OOOW',
        'W  B WW B  W  OOOOW',
        'WW WWWWW WWW WWOWWW',
        'WW   B  B WW   O  W',
        'W BWWW  W WWWWW WWW',
        'W   B   W       W  ',
        'W  B WB B BWWW  W  ',
        'W BBBW B   W WWWW  ',
        'W    W  BB W       ',
        'WWWWWW   WWW       ',
        '     WWWWW         '],
    map40: [
        '     WWWWWWWWWWWW  ',
        '     W          WW ',
        '     W  W WBB B  W ',
        '     WB WBW  WW SW ',
        '    WW WW W B W WW ',
        '    W   B WB  W W  ',
        '    W   W B   W W  ',
        '    WW B B   WW W  ',
        '    W  W  WW  B W  ',
        '    W    WW BBW W  ',
        ' WWWWWWBB   W   W  ',
        ' WOOOOW  WWWWWWWW  ',
        ' WOWOOO WW         ',
        ' WOOOO   W         ',
        ' WOOOO   W         ',
        ' WWWWWWWWW         '],
    map41: [
        '           WWWWW   ',
        '          WW   WW  ',
        '         WW     W  ',
        '        WW  BB  W  ',
        '       WW BB  B W  ',
        '       W B    B W  ',
        'WWWW   W   BB WWWWW',
        'W  WWWWWWWW WW    W',
        'WO            BBBSW',
        'WOW WWWWWWW WW   WW',
        'WOW WWWWWWWO WB BWW',
        'WOOOOOOOOOOO W    W',
        'WWWWWWWWWWWWWW  B W',
        '             WW  WW',
        '              WWWW '],
    map42: [
        '      WWWWWWWW     ',
        '   WWWW      WWWWWW',
        '   W    WW B B   SW',
        '   W WW WWBWB B BWW',
        ' WWW OOOOOOW  BB WW',
        ' W   OOOOOOW  W   W',
        ' W W OOOOOOWB  B  W',
        ' W W OOOOOO BBW B W',
        ' W  BWWW WWWB  B WW',
        ' WWW  B  B  B  B W ',
        '   W   B B  B  B W ',
        '   WWWWWW   WWWWWW ',
        '        WWWWW      '],
    map43: [
        '        WWWWWWW    ',
        '    WWWWW  W  WWWW ',
        '    W   W   B    W ',
        ' WWWW WBB WW WW  W ',
        'WW      W W  WW WWW',
        'W  WWW BWB  B  B  W',
        'WOOO    W WW  W   W',
        'WOOOW    S W WWW WW',
        'WOOOW  WWW  B  B  W',
        'WWWWWWWW WW   W   W',
        '          WWWWWWWWW'],
    map44: [
        ' WWWWW             ',
        ' W   W             ',
        ' W W WWWWWWW       ',
        ' W      BSWWWWWW   ',
        ' W B WWB WWW   W   ',
        ' W WWWW B    B W   ',
        ' W WWWWW W  WB WWWW',
        'WW  WWWW WWB      W',
        'W  BW  B  W WW WW W',
        'W         W WOOOW W',
        'WWWWWW  WWW  OOO  W',
        '     WWWW W WOOOW W',
        '          W WWW W W',
        '          W       W',
        '          WWWWWWWWW'],
    map45: [
        '  WWWWW WWWW       ',
        '  WOOOW W  WWWW    ',
        '  WOOOWWW  B  W    ',
        '  WOOOOWW B  BWWW  ',
        '  WWOOOOWW   B  W  ',
        '  WWWOOO WW B B W  ',
        '  W WW    W  B  W  ',
        '  W  WW W WWW WWWW ',
        '  W B W WB  B    W ',
        '  W  B S B    B  W ',
        '  W   W B BB B WWW ',
        '  W  WWWWWW  WWW   ',
        '  W WW    WWWW     ',
        '  WWW              '],
    map46: [
        '   WWWWWWWWWW      ',
        '   W        WWWW   ',
        '   W WWWWWW W  WW  ',
        '   W W B B B  B W  ',
        '   W       WB   W  ',
        '   WWWB  BBW  WWW  ',
        '     W  WW W BWW   ',
        '     WWBW   B SW   ',
        '      W  B B WWW   ',
        '      W W   B  W   ',
        '      W WW   W W   ',
        '     WW  WWWWW W   ',
        '     W         W   ',
        '     WOOOOOOOWWW   ',
        '     WOOOOOOOW     ',
        '     WWWWWWWWW     '],
    map47: [
        '          WWWW     ',
        '  WWWWWWWWW  WW    ',
        ' WW  B      B WWWWW',
        ' W   WW WW   WWOOOW',
        ' W WBB B BBWBWWOOOW',
        ' W W    S  W   OOOW',
        ' W  BW WWWBB   OOOW',
        ' W B  BB  B WWOOOOW',
        ' WWWB       WWWWWWW',
        '   W  WWWWWWW      ',
        '   WWWW            '],
    map49: [
        '     WWWWWWWWW     ',
        '     WXOXWXOXW     ',
        '     WOXOXOXOW     ',
        '     WXOXOXOXW     ',
        '     WOXOXOXOW     ',
        '     WXOXOXOXW     ',
        '     WWW   WWW     ',
        '       W   W       ',
        '   WWWWWW WWWWWW   ',
        '   W           W   ',
        '   W B B B B B W   ',
        '   WW B B B B WW   ',
        '    WB B B B BW    ',
        '    W   BSB   W    ',
        '    W  WWWWW  W    ',
        '    WWWW   WWWW    '],
    map49: [
        '         WWWW      ',
        '         W  WW     ',
        '         W   WW    ',
        '         W BB WW   ',
        '       WWWB  B WW  ',
        '    WWWW    B   W  ',
        '  WWW  W WWWWW  W  ',
        '  W    W WOOOOB W  ',
        '  W W   B OOOOW W  ',
        '  W  B W WOXOOW W  ',
        '  WWW  WWWW WWW W  ',
        '    WWWW SB  WWBWW ',
        '       WWW B     W ',
        '         W  WW   W ',
        '         WWWWWWWWW '],
    map50: [
        '      WWWWWWWWWWWW ',
        '     WWOO    W   W ',
        '    WWOOX B    B W ',
        '   WWOOXOW W WB WW ',
        '   WOOXOW W W B  W ',
        'WWWWOOOW  W    W W ',
        'W  WW W          W ',
        'W SB B WWW  W W WW ',
        'W B   B   W W   W  ',
        'WWWBB   W W W W W  ',
        '  W   B   W W WWWWW',
        '  W BW WWWWW      W',
        '  WB   W   W   W  W',
        '  W  WWW   WW     W',
        '  W  W      W    WW',
        '  WWWW      WWWWWW ']
    }
    